
name: "  Godot 3.2.0  "

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 3.2.0
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:3.2
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: godot addons/WAT/cli.tscn -run_all
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: tests/results.xml