name: "  Godot 3.5  "

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 3.5
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:mono-3.5
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
      - name: Compile
        run: msbuild
      - name: Run
        run: godot addons/WAT/cli.tscn run=all
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: tests/results.xml